# Generated by Django 4.2.3 on 2023-08-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_question_created_at_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
